apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-service-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bff-service
  template:
    metadata:
      labels:
        app: bff-service
    spec:
      containers:
        - name: bff-service
          image: nicolajh/swj-bff
          ports:
            - containerPort: 8080
          env:
            - name: URL_JOBSERVICE
              value: http://job-service:8080/api/jobs
            - name: URL_AUTHENTICATIONSERVICE
              value: http://authentication-service:3000
            - name: URL_COMPANYSERVICE
              value: http://company-service:8080/api/companies
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: jwtsecret
                  key: secret
          resources:
            limits:  
              cpu: "500m"
              memory: "500Mi"
            requests:  
              cpu: "500m"
              memory: "500Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: bff-service
spec:
  selector:
    app: bff-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-bff
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bff-service-deployment
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80